name: shopcaycanh
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  foundation:
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/Images/
    - .env
  uses-material-design: true
  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
  - family: Anton
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf